# Generated by Django 3.0.8 on 2020-08-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=120)),
                ('last_name', models.TextField(max_length=120)),
                ('phone_number', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
